[[redirects]]
  from = "https://listen.wmhdradio.org/*"
  to = "https://wmhdradio.org"
  status = 301
  force = false

[[redirects]]
  from = "https://listen.wmhdradio.com/*"
  to = "https://wmhdradio.com"
  status = 301
  force = false

[[redirects]]
  from = "http://listen.wmhdradio.org/*"
  to = "http://wmhdradio.org"
  status = 301
  force = false

[[redirects]]
  from = "http://listen.wmhdradio.com/*"
  to = "http://wmhdradio.com"
  status = 301
  force = false